[versions]
# libraries
spring-boot = "4.0.1"
spring-cloud = "2025.1.0"
cosid = "3.0.2"
cocache = "4.0.1"
opentelemetry = "2.24.0"
testcontainers = "2.0.3"
guava = "33.5.0-jre"
kotlin-logging = "7.0.14"
ognl = "3.4.10"
java-jwt = "4.5.0"
ip2region = "3.3.3"
justAuth = "1.16.7"
swagger = "2.2.41"
springdoc = "3.0.0"
# testing
junit = "6.0.2"
fluent-assert = "0.2.6"
hamcrest = "3.0"
mockk = "1.14.7"
jmh = "1.37"
# plugins
detekt = "1.23.8"
dokka = "2.1.0"
kotlin = "2.3.0"
publish-plugin = "2.0.0"
jmh-plugin = "0.7.3"
[libraries]
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-cloud-dependencies = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "spring-cloud" }
cosid-bom = { module = "me.ahoo.cosid:cosid-bom", version.ref = "cosid" }
cocache-bom = { module = "me.ahoo.cocache:cocache-bom", version.ref = "cocache" }
opentelemetry-instrumentation-bom = { module = "io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom", version.ref = "opentelemetry" }
testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
ognl = { module = "ognl:ognl", version.ref = "ognl" }
java-jwt = { module = "com.auth0:java-jwt", version.ref = "java-jwt" }
ip2region = { module = "org.lionsoul:ip2region", version.ref = "ip2region" }
justAuth = { module = "me.zhyd.oauth:JustAuth", version.ref = "justAuth" }
swagger = { module = "io.swagger.core.v3:swagger-core-jakarta", version.ref = "swagger" }
springdoc-bom = { module = "org.springdoc:springdoc-openapi-bom", version.ref = "springdoc" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
fluent-assert-bom = { module = "me.ahoo.test:fluent-assert-bom", version.ref = "fluent-assert" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
jmh-core = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }
jmh-generator-annprocess = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh" }
[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "publish-plugin" }
jmh = { id = "me.champeau.jmh", version.ref = "jmh-plugin" }

